name: bisaapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  get: ^4.7.3
  intl: ^0.20.2
  supabase_flutter: ^2.12.4
  excel: ^4.0.6
  csv: ^6.0.0
  path_provider: ^2.1.4
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"